apiVersion: v1
kind: Secret
metadata:
  name: customer-service-db-secret
  namespace: customer-service
type: Opaque
stringData:
  DB_USER: postgres
  DB_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
